### ISSUE TITLE
Core AlbumDrop Contract

### ISSUE THREAD

**Issue by jMyles** [JustinHolmesMusic/VowelSoundsAlbumDrop#1]
This is probably more like a project than an issue, but we'll start here.

Attributes (in addition to the usual):

* `unlock_price`
* `minimum_contribution`
* `extension_duration`
* `is_released`

So we imagine something like

`function contribute(...) public payable` ?

And it will take `preferred_serial0`, `preferred_serial1`, and perhaps some related preference metadata?

And then a function which checks the contribution total and ticks `is_released`?  Or do we do this in the same function?  I'm not great at estimating gas yet.

**Comment by kubic71** [comment]
@jMyles
Can we close this one?
