### ISSUE TITLE
Contribute buttons needs pointer to change to the hand

### ISSUE THREAD

**Issue by rjpartingtoniii** [JustinHolmesMusic/VowelSoundsAlbumDrop#43]

**Comment by kubic71** [comment]
@rjpartingtoniii Do we have some details?

**Comment by rjpartingtoniii** [comment]
@kubic71, yes :), for the UE, most of the time while using a desktop computer, the user will be controlling a pointer. While it hovers over the "contribute buttons" we would like for that pointer to appear as a hand.
