### ISSUE TITLE
CSS needs rework; display text was being overridden 

### ISSUE THREAD

**Issue by jMyles** [JustinHolmesMusic/VowelSoundsAlbumDrop#48]
While viewing the app as it looks as of #46, it appears that the elements are in a strange order (with `left-side` appearing before the other elements):

![image](https://github.com/JustinHolmesMusic/VowelSoundsAlbumDrop/assets/311973/d3e3721a-5a57-4373-991c-4fa7decef0c2)

This is because our own `styles.css` file is now controlling the tag-level selectors.

Previously, I believe @KPrasch believed that `main` was `display: flex`, but this was mistaken: bootstrap was overriding this setting and causing it to be `display:block`, and it was only this that was producing the correct order.

So... I suppose we can either change it to `display:block` or figure out how to make this flex work.

**Comment by kubic71** [comment]
In my PR #21 I changed the order of inclusion of `.css` files: first `bootstrap`'s css and then our `style.css`, because the boostrap was overriding our styles in `style.css`.

Not sure if that's relevant to this issue.

**Comment by jMyles** [comment]
Fixed by various subsequent actions - #53 #55 #56 #57 #58
