### ISSUE TITLE
"x" button & "close" buttons do not work on "Get Encrypted Record" modal

### ISSUE THREAD

**Issue by rjpartingtoniii** [JustinHolmesMusic/VowelSoundsAlbumDrop#63]
"x" button & "close" buttons do not work
IPFS, Arweave & Bittorrent buttons do not work

<img width="1321" alt="Screen Shot 2023-08-21 at 10 37 25 AM" src="https://github.com/JustinHolmesMusic/VowelSoundsAlbumDrop/assets/78699050/785f5b77-b3de-4452-931d-d7208cabf573">

**Comment by kubic71** [comment]
Let's close this @jMyles

**Comment by rjpartingtoniii** [comment]
Aweomse, @kubic71 !
