### ISSUE TITLE
Reading the contract is not reliable

### ISSUE THREAD

**Issue by kubic71** [JustinHolmesMusic/VowelSoundsAlbumDrop#80]
From time to time the `readContract` functions throws an exception.

![image](https://github.com/JustinHolmesMusic/VowelSoundsAlbumDrop/assets/12272640/a2f7a0e4-158f-4823-9b6e-906ec3dc039b)

Do we want to do something with that, or do we fail silently relying on the next request to be successful?

**Comment by jMyles** [comment]
I think what's happening here is that the public provider that WAGMI is choosing by default isn't always one that allows calling of the default getter function.

I wish it weren't true, but using infura seems to make the problem go away.  

For medium-term, I'm definitely interested in hearing ways to do this in a decentralized fashion.  @owocki is at or near the cutting edge of this.  Maybe he has some thoughts.

**Comment by jakubhejhal** [comment]
Fixed by #82 
Let's close this @jMyles
