### ISSUE TITLE
Combine my contribution button needs to be centered 

### ISSUE THREAD

**Issue by rjpartingtoniii** [JustinHolmesMusic/VowelSoundsAlbumDrop#90]
<img width="1051" alt="Screen Shot 2023-08-29 at 12 56 32 PM" src="https://github.com/JustinHolmesMusic/VowelSoundsAlbumDrop/assets/78699050/e0f4dfe6-015e-4883-8e2a-2da122952772">

**Comment by kubic71** [comment]
No longer relevant, we're using contribute modal.
Closing.
